---
title: "analysis"
author: "Yifan Duan"
date: "2024-09-05"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
library(Seurat)
library(BPCells)
library(dplyr)
library(ggplot2)
library(ggrepel)
library(patchwork)
library(Matrix)
library(cowplot)
library(irlba)
# set this option when analyzing large datasets
options(future.globals.maxSize = 3e+09)

neuron_obj <- readRDS("data/neuron.Rds")
```


```{r}
# find variable genes with Seurat
neuron_obj <- FindVariableFeatures(neuron_obj, selection.method = "vst", nfeatures = 2000)
top10 <- head(VariableFeatures(neuron_obj), 10)

plot1 <- VariableFeaturePlot(neuron_obj)
plot2 <- LabelPoints(plot = plot1, points = top10, repel = TRUE)
plot2

# selecting top 2000 variable genes
neuron_mat <- neuron_obj@assays$RNA$counts
neuron_mat_norm <- neuron_mat[VariableFeatures(neuron_obj),]

# saves time according to BPCells
neuron_mat_norm <- neuron_mat_norm %>% write_matrix_dir(tempfile("mat"))
```


```{r}
# PCA
svd <- BPCells::svds(neuron_mat_norm, k = 50)
#svd <- irlba(neuron_mat_norm, nv=50)
pca <- multiply_cols(svd$v, svd$d)

colnames(pca) <- paste0("PC_", 1:ncol(pca))
rownames(pca) <- colnames(neuron_mat_norm)

neuron_obj[["pca"]] <- CreateDimReducObject(embeddings = pca, key = "PC_", 
                                         assay = DefaultAssay(neuron_obj))

plot(svd$d / sqrt(nrow(neuron_mat_norm)))
```


```{r}
# UMAP
set.seed(123)
umap <- uwot::umap(pca)

colnames(umap) <- paste0("UMAP_", 1:2)
rownames(umap) <- colnames(neuron_mat_norm)

neuron_obj[["umap"]] <- CreateDimReducObject(embeddings = umap, key = "UMAP_", 
                                         assay = DefaultAssay(neuron_obj))

DimPlot(neuron_obj, reduction = "umap", group.by = "Cluster.Label")
```


```{r}
# clustering
neuron_obj <- FindNeighbors(neuron_obj, dims = 1:50)
# Define the range of resolutions
resolutions <- c(0.2)

# Loop through the resolutions and store clustering results in Seurat object's metadata
for (res in resolutions) {
  neuron_obj <- FindClusters(neuron_obj, resolution = res, 
                             verbose = FALSE, method = "igraph",
                             algorithm = 4) # leiden
  
  # Store the clustering results with a label corresponding to the resolution
  #cluster_column <- paste0("RNA_snn_res.", res)
}

DimPlot(neuron_obj, reduction = "umap", group.by = "cell_type__ontology_label")
DimPlot(neuron_obj, reduction = "umap", group.by = "donor_id")

```


```{r}
# add the count to data layer would fix it
neuron_obj[["RNA"]]$data <- neuron_obj[["RNA"]]$counts

Idents(neuron_obj) <- "RNA_snn_res.0.2"
#FindMarkers(neuron_obj, ident.1 = "6", assay = "RNA")

dim(neuron_obj[["RNA"]]$counts)

FeaturePlot(neuron_obj, features = c("Omp", "Stoml3", "Cnga2", "Adcy3"))
```


```{r investigating doublet}
# 1. higher counts than the rest
# 2. mixture of markers 
grp6_marker <- FindMarkers(neuron_obj, ident.1 = "6", assay = "RNA")
doublet_obj <- subset(neuron_obj, subset = RNA_snn_res.0.2 == "6")

library(EnhancedVolcano)
pdf("figure/DE_genes_grp6.pdf")
EnhancedVolcano(grp6_marker, 
                rownames(grp6_marker),
                x ="avg_log2FC", 
                y ="p_val_adj")
dev.off()

DimPlot(doublet_obj, reduction = "umap", group.by = "Cluster.Label")
cluster_table <- table(doublet_obj$Cluster.Label)
cluster_table <- cluster_table[cluster_table != 0]

VlnPlot(neuron_obj, features = "nCount_RNA", group.by = "seurat_clusters")
VlnPlot(neuron_obj, features = "nFeature_RNA", group.by = "seurat_clusters")

library(DoubletFinder)
neuron_obj <- doubletFinder_v3(neuron_obj, PCs = 1:10, pN = 0.25, pK = best_pK, nExp = 500)


```


```{r}
saveRDS(neuron_obj, file = "data/neuron.Rds")

FeaturePlot(neuron_obj, features = c("Nqo1","Acsm4", "Nfix", "Ncam2"))
# dorsal acsm4, nqo1
# ventral nfix, ncam2

mature_neuron_obj <- subset(neuron_obj, subset = RNA_snn_res.0.2 == c("1", "2", "4", "6"))
saveRDS(mature_neuron_obj, "data/mature_neuron.Rds")
```

